name: my_flutter
description: A new flutter module project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  json_annotation: ^4.0.1
  json_serializable: ^4.1.2
  build_runner: ^2.0.3

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  json_annotation: ^2.4.0
  flutter_easyloading: ^3.0.0
  dio: ^4.0.0
  provider: ^4.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.my_flutter
    iosBundleIdentifier: com.example.myFlutter
  assets:
    - assets/imgs/nothing.png